### PR TITLE
Remove Performance/EmptyGsubReplacement cop

### PR DESCRIPTION
**Pull request by avit**
The suggestion to use `String#delete` is not equivalent to `gsub("WORD", "")`:

    "What Our Rule Deletes".delete("WORD")
    #=> "hat ur ule eletes"

### CODE REVIEW

**Comment by vlyandra** [comment]
I'm pretty sure this only triggers when you're doing something that String#delete can do, such as `'This is a string'.gsub('s', '')` rather than `'This is a string'.gsub('string', '')`

**Comment by avit** [comment]
The pattern has a `+` in it, so it matches any number of characters:

https://github.com/aha-app/rubocop-aha/pull/35/files#diff-7d23687dd4f4ff95f93f07cae2c2df35L26

Or, do you think there's a reason to enforce a different style between single- and multi-character replacements?

**Comment by vlyandra** [comment]
Honestly, I'm not sure if it's worth enforcing String#delete over gsub for single character deletions, but it does look like that's what it cares about: https://github.com/aha-app/rubocop-aha/pull/35/files#diff-7d23687dd4f4ff95f93f07cae2c2df35L95

I'm going to guess that we aren't crunching for performance to that extent so I'm fine with removing it, just wanted to point out that the suggestion isn't incorrect, per se, just probably not necessary.

**Comment by avit** [comment]
Good catch @vlyandra I looked at the regex and missed that length check further down...

We could probably keep this if it's worthwhile, but I'd at least change the message to add `"for single characters"` since this reads like a blanket statement to `"use delete instead of gsub"` in every situation.

**Comment by avit** [comment]
There's also a built-in one for this:

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Performance/StringReplacement

It looks like it does the same as ours, so we could just go with that instead.

**Comment by avit** [comment]
Discussed with @schneidmaster: the unqualified admonition to "use delete" or "use tr" from this cop or the built-in one are not worth the risk of introducing bugs. The performance gains are minimal.

**Pull request merged**
